export interface Carga {
  cargaRut: string,
  cargaDigito: string,
  nombreCarga: string,
  edadCarga: number,
  sexoCarga: string,
  montoCupon: number,
  estadoCupon: string,
  fecEstado: string,
  tipoCanje: null,
  nomComercio: string,
  tipoEntrega: null,
  dirDespacho: null,
  comunaDespacho: null,
  regionDespacho: null,
  estadoDespacho: null,
  fecEstadoDespacho: null,
  idConvenio: number,
  codigoCupon: string,
  idBeneficio: number,
}
